using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pes2021Api
{
    public static class Countries
    {
        public static string Get(uint id)
        {
            return Get((int)id);
        }

        public static string Get(int id)
        {
            switch (id)
            {
                case 1: return "AFGHANISTAN";
                case 2: return "BAHRAIN";
                case 3: return "BANGLADESH";
                case 4: return "BHUTAN";
                case 5: return "BRUNEI DARUSSALAM";
                case 6: return "CAMBODIA";
                case 7: return "CHINA";
                case 8: return "HONG KONG";
                case 9: return "INDIA";
                case 10: return "INDONESIA";
                case 11: return "IRAN";
                case 12: return "IRAQ";
                case 13: return "JAPAN";
                case 14: return "JORDAN";
                case 15: return "KOREA DPR";
                case 16: return "REPUBLIC OF KOREA";
                case 17: return "KUWAIT";
                case 18: return "LAOS";
                case 19: return "LEBANON";
                case 20: return "MACAU";
                case 21: return "MALAYSIA";
                case 22: return "MALDIVES";
                case 23: return "MONGOLIA";
                case 24: return "MYANMAR";
                case 25: return "NEPAL";
                case 26: return "OMAN";
                case 27: return "PAKISTAN";
                case 28: return "PALESTINE";
                case 29: return "PHILIPPINES";
                case 30: return "QATAR";
                case 31: return "SAUDI ARABIA";
                case 32: return "SINGAPORE";
                case 33: return "SRI LANKA";
                case 34: return "SYRIA";
                case 36: return "THAILAND";
                case 37: return "UNITED ARAB EMIRATES";
                case 38: return "VIETNAM";
                case 39: return "YEMEN";
                case 40: return "KYRGYZSTAN";
                case 41: return "TAJIKISTAN";
                case 42: return "TURKMENISTAN";
                case 43: return "TIMOR-LESTE";
                case 44: return "ALGERIA";
                case 45: return "ANGOLA";
                case 46: return "BENIN";
                case 47: return "BOTSWANA";
                case 48: return "BURKINA FASO";
                case 49: return "BURUNDI";
                case 50: return "CAMEROON";
                case 51: return "CAPE VERDE";
                case 52: return "CENTRAL AFRICAN REP.";
                case 53: return "CHAD";
                case 54: return "COMOROS";
                case 55: return "CONGO DR";
                case 56: return "CÃ?TE D'IVOIRE";
                case 57: return "DJIBOUTI";
                case 58: return "EGYPT";
                case 59: return "EQUATORIAL GUINEA";
                case 60: return "ERITREA";
                case 61: return "ETHIOPIA";
                case 62: return "GABON";
                case 63: return "GAMBIA";
                case 64: return "GHANA";
                case 65: return "GUINEA";
                case 66: return "GUINEA-BISSAU";
                case 67: return "KENYA";
                case 68: return "LESOTHO";
                case 69: return "LIBERIA";
                case 70: return "LIBYA";
                case 71: return "MADAGASCAR";
                case 72: return "MALAWI";
                case 73: return "MALI";
                case 74: return "MAURITANIA";
                case 75: return "MAURITIUS";
                case 76: return "MOROCCO";
                case 77: return "MOZAMBIQUE";
                case 78: return "NAMIBIA";
                case 79: return "NIGER";
                case 80: return "NIGERIA";
                case 81: return "RWANDA";
                case 82: return "SAO TOME AND PRINCIPE";
                case 83: return "SENEGAL";
                case 84: return "SEYCHELLES";
                case 85: return "SIERRA LEONE";
                case 86: return "SOMALIA";
                case 87: return "SOUTH AFRICA";
                case 88: return "SUDAN";
                case 89: return "ESWATINI";
                case 90: return "TANZANIA";
                case 91: return "TOGO";
                case 92: return "TUNISIA";
                case 93: return "UGANDA";
                case 94: return "ZAMBIA";
                case 95: return "ZIMBABWE";
                case 98: return "CONGO";
                case 103: return "ANGUILLA";
                case 104: return "ANTIGUA AND BARBUDA";
                case 105: return "ARUBA";
                case 106: return "BAHAMAS";
                case 107: return "BARBADOS";
                case 108: return "BELIZE";
                case 109: return "BERMUDA";
                case 110: return "CANADA";
                case 111: return "CAYMAN ISLANDS";
                case 112: return "COSTA RICA";
                case 113: return "CUBA";
                case 114: return "DOMINICA";
                case 115: return "DOMINICAN REPUBLIC";
                case 116: return "EL SALVADOR";
                case 117: return "GRENADA";
                case 119: return "GUATEMALA";
                case 120: return "HAITI";
                case 121: return "HONDURAS";
                case 122: return "JAMAICA";
                case 124: return "MEXICO";
                case 125: return "MONTSERRAT";
                case 127: return "NICARAGUA";
                case 128: return "PANAMA";
                case 129: return "PUERTO RICO";
                case 130: return "SAINT KITTS AND NEVIS";
                case 131: return "SAINT LUCIA";
                case 132: return "ST VINCENT & GRENADINES";
                case 133: return "TRINIDAD AND TOBAGO";
                case 134: return "TURKS AND CAICOS IS.";
                case 135: return "USA";
                case 136: return "BRITISH VIRGIN ISLANDS";
                case 137: return "US VIRGIN ISLANDS";
                case 139: return "SURINAME";
                case 140: return "CURAÃ?AO";
                case 144: return "ARGENTINA";
                case 145: return "BOLIVIA";
                case 146: return "BRAZIL";
                case 147: return "CHILE";
                case 148: return "COLOMBIA";
                case 149: return "ECUADOR";
                case 150: return "PARAGUAY";
                case 151: return "PERU";
                case 152: return "URUGUAY";
                case 153: return "VENEZUELA";
                case 159: return "GUYANA";
                case 161: return "AMERICAN SAMOA";
                case 162: return "AUSTRALIA";
                case 163: return "COOK ISLANDS";
                case 164: return "FIJI";
                case 165: return "NEW CALEDONIA";
                case 166: return "NEW ZEALAND";
                case 167: return "PAPUA NEW GUINEA";
                case 168: return "SAMOA";
                case 169: return "SOLOMON ISLANDS";
                case 170: return "TAHITI";
                case 171: return "TONGA";
                case 172: return "VANUATU";
                case 176: return "GUAM";
                case 184: return "PALAU";
                case 189: return "ISRAEL";
                case 190: return "TURKEY";
                case 191: return "ALBANIA";
                case 192: return "ANDORRA";
                case 193: return "ARMENIA";
                case 194: return "AUSTRIA";
                case 195: return "AZERBAIJAN";
                case 196: return "BELARUS";
                case 197: return "BELGIUM";
                case 198: return "BOSNIA AND HERZEGOVINA";
                case 199: return "BULGARIA";
                case 200: return "CROATIA";
                case 201: return "CYPRUS";
                case 202: return "CZECH REPUBLIC";
                case 203: return "DENMARK";
                case 204: return "ENGLAND";
                case 205: return "ESTONIA";
                case 206: return "FAROE ISLANDS";
                case 207: return "FINLAND";
                case 208: return "FRANCE";
                case 209: return "GEORGIA";
                case 210: return "GERMANY";
                case 211: return "GREECE";
                case 212: return "HUNGARY";
                case 213: return "ICELAND";
                case 214: return "IRELAND";
                case 215: return "ITALY";
                case 216: return "KAZAKHSTAN";
                case 217: return "LATVIA";
                case 218: return "LIECHTENSTEIN";
                case 219: return "LITHUANIA";
                case 220: return "LUXEMBOURG";
                case 221: return "NORTH MACEDONIA";
                case 222: return "MALTA";
                case 223: return "MOLDOVA";
                case 224: return "NETHERLANDS";
                case 225: return "NORTHERN IRELAND";
                case 226: return "NORWAY";
                case 227: return "POLAND";
                case 228: return "PORTUGAL";
                case 229: return "ROMANIA";
                case 230: return "RUSSIA";
                case 231: return "SAN MARINO";
                case 232: return "SCOTLAND";
                case 234: return "SLOVAKIA";
                case 235: return "SLOVENIA";
                case 236: return "SPAIN";
                case 237: return "SWEDEN";
                case 238: return "SWITZERLAND";
                case 239: return "UKRAINE";
                case 240: return "UZBEKISTAN";
                case 241: return "WALES";
                case 245: return "GIBRALTAR";
                case 250: return "MONACO";
                case 260: return "Others";
                case 298: return "CHINESE TAIPEI";
                case 303: return "SERBIA";
                case 304: return "MONTENEGRO";
                case 311: return "KOSOVO";
                case 312: return "SOUTH SUDAN";

                default:
                    return "No Country";

            }
        }
    }
}
